spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    username: user
    url: jdbc:postgresql://localhost:5433/products_db
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

